# configuration

title: Luyu Huang's tech blog
email: luyu_huang@foxmail.com
rss: rss
description: >-
  I'm a software engineer and game developer. Here I would like share my learning, insights and growth.

author: Luyu Huang
github_username:  luyuhuang

theme: minima
minima:
  date_format: "%Y-%m-%d"

kramdown:
  math_engine: null

header_pages:
  - featured.md
  - categories.html
  - about.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

show_excerpts: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
  - jekyll-feed
